- params:
    git:
      repoName: flask-webgoat
      branches:
        - master
      aggregateFixes: false
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: false
      projects:
        - pipRequirementsFile: "requirements.txt"
          projectName: "project#1"
        - pipRequirementsFile: "build-requirements.txt"
          projectName: "project#2"