- params:
    git:
      repoName: flask-webgoat
      branches:
        - master
      aggregateFixes: false
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: false
      projects:
        - pipRequirementsFile: "requirements.txt"
          projectName: "b4ef698db8ca845e5845c4618278f29a"
        - pipRequirementsFile: "build-requirements.txt"
          projectName: "70f2354004219e7036832f665ff35716"