- params:
    git:
      repoName: flask-webgoat
      branches:
        - master
      aggregateFixes: true
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: false
      projects:
        - pipRequirementsFile: "requirements.txt"
          uniqueIdentifier: "requirements.txt"
        - pipRequirementsFile: "build-requirements.txt"
          uniqueIdentifier: "build-requirements.txt"