- params:
    git:
      repoName: my-repo
      branches:
        - master
      aggregateFixes: true
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: false
      projects:
        - pipRequirementsFile: "requirements.txt"
          uniqueIdentifier: "b4ef698db8ca845e5845c4618278f29a"
        - pipRequirementsFile: "build-requirements.txt"
          uniqueIdentifier: "70f2354004219e7036832f665ff35716"